azure:
  resource_group: "rg-test"

app_insights:
  instrumentation_key: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}

policies:
  policy_file: "policies/policies.yaml"
  schema_file: "src/schema.json"
