name: Azure Cost Optimization Workflow Dry Run

on:
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "CONFIG_FILE=configs/config.yaml" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=38c26c07-ccce-4839-b504-cddac8e5b09d" >> $GITHUB_ENV
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "APPINSIGHTS_INSTRUMENTATIONKEY=${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_ACCOUNT_NAME= ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME  }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_FILE_SYSTEM_NAME= ${{ secrets.AZURE_STORAGE_FILE_SYSTEM_NAME  }}" >> $GITHUB_ENV
          echo "ADLS_DIRECTORY_PATH= ${{ secrets.ADLS_DIRECTORY_PATH  }}" >> $GITHUB_ENV
          echo "GH_PATNEW= ${{ secrets.GH_PATNEW  }}"

      - name: Verify environment variables
        run: |
          echo "CONFIG_FILE=$CONFIG_FILE"
          echo "AZURE_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID"
          echo "AZURE_CLIENT_ID=$AZURE_CLIENT_ID"
          echo "AZURE_TENANT_ID=$AZURE_TENANT_ID"
          echo "AZURE_CLIENT_SECRET=$AZURE_CLIENT_SECRET"
          echo "APPINSIGHTS_INSTRUMENTATIONKEY=$APPINSIGHTS_INSTRUMENTATIONKEY"
          echo "AZURE_STORAGE_ACCOUNT_NAME= ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME  }}"
          echo "AZURE_STORAGE_FILE_SYSTEM_NAME= ${{ secrets.AZURE_STORAGE_FILE_SYSTEM_NAME  }}"
          echo "ADLS_DIRECTORY_PATH= ${{ secrets.ADLS_DIRECTORY_PATH  }}"
          echo "GH_PATNEW= ${{ secrets.GH_PATNEW  }}"

      - name: Run Azure Cost Optimizer in Dry Mode
        env:
          CONFIG_FILE: configs/config.yaml
          AZURE_SUBSCRIPTION_ID: 38c26c07-ccce-4839-b504-cddac8e5b09d
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME  }}
          AZURE_STORAGE_FILE_SYSTEM_NAME: ${{ secrets.AZURE_STORAGE_FILE_SYSTEM_NAME  }}
          ADLS_DIRECTORY_PATH: ${{ secrets.ADLS_DIRECTORY_PATH  }}
          GH_PATNEW: ${{ secrets.GH_PATNEW  }}

        run: |
          echo "Running Python script with mode dry-run"
          python src/main.py --mode dry-run --all-subscriptions

      - name: Configure Git
        if: ${{ success() }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Create a new branch and commit changes
        if: ${{ success() && env.HAS_CHANGES == 'yes'}}
        run: |
          BRANCH_NAME=ACO-$(date +'%Y%m%d%H%M%S')
          git checkout -b $BRANCH_NAME
          git add impacted_resources.txt
          git add cost_trend_*.png
          git commit -m "Add impacted_resources.txt and cost trend charts"
          git push origin $BRANCH_NAME
      - name: Create a new issue and a Pull Request
        if: ${{ success() && env.HAS_CHANGES == 'yes'}}
        run: |
          gh issue create --title "Azure Cost Optimization Results" --body "This issue contains automated changes by the Release Copilot workflow." --label "notification"
          gh pr create --base main --head "$BRANCH_NAME" --title "Automated changes by Azure Cost Optimizer" --body "This PR contains automated changes by the Azure Cost Optimizer." --label "notification"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PATNEW }}          
      # - name: Notify Owner via GitHub Issue.
      #   if: success()
      #   uses: peter-evans/create-issue-from-file@v3
      #   with:
      #     title: "Azure Cost Optimization Results"
      #     content-filepath: impacted_resources.txt
      #     labels: |
      #       notification
