name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
    # - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: windows-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify environment variables
      shell: pwsh
      run: |
          echo "AZURE_CLIENT_ID=$env:AZURE_CLIENT_ID"
          echo "AZURE_TENANT_ID=$env:AZURE_TENANT_ID"
          echo "AZURE_CLIENT_SECRET=$env:AZURE_CLIENT_SECRET"
    - name: Run Cost Optimizer in Dry Run Mode
      run: |
        python src/main.py --mode dry-run
      env:
        CONFIG_FILE: "configs/config.yaml"
        APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
